exclude_paths:
  - "test/*"
  - "docs/*"
  - "vendor/*"
engines:
  duplication:
    enabled: true
    checks:
      Identical code:
        enabled: false
  config:
    languages:
    - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortMethodName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
  - "**.php"
